<?php
$row_projet_173912757656 = 
array(
    array(
        "id_projet" => "1",
        "activation_projet" => "",
        "id_general" => "",
        "id_user_projet" => "1",
        "id_sha1_user_projet" => "1739127412",
        "id_sha1_projet" => "173912757656",
        "color_projet" => "",
        "google_title_projet" => "",
        "level_urgence_projet" => "",
        "change_meta_name_projet" => "",
        "change_meta_content_projet" => "",
        "id_sha1_parent_projet" => "",
        "id_sha1_parent_projet2" => "",
        "cryptage_projet" => "",
        "html_mode_projet" => "",
        "style_pages_projet" => "1739127605_875",
        "name_pages_projet" => "",
        "input_cryptage_projet" => "",
        "name_projet" => "",
        "name_extention_projet" => ".jpeg",
        "statue_projet" => "",
        "title_projet" => "",
        "description_projet" => "",
        "password_projet" => "",
        "visibility_1_projet" => "(0-0)",
        "visibility_2_projet" => "",
        "screen_shoot_projet" => "",
        "img_projet_src1" => "../src/img/1739127412/1739131488.jpeg",
        "img_projet_src2" => "",
        "img_projet_visibility" => "",
        "groupe_projet" => "",
        "heure_debut_projet" => "",
        "date_debut_projet" => "",
        "dure_projet" => "",
        "publication_date_j_projet" => "",
        "publication_date_h_projet" => "",
        "shop_projet" => "",
        "date_inscription_projet" => "2025-02-09 22:07:27",
    ),
);
?>